name: Build Python Wheels

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write  # Required for publishing to PyPI with trusted publishing

jobs:
  prepare-version:
    name: Extract Version from Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Extract version from tag
        id: extract-version
        run: |
          TAG_VERSION="${{ github.ref_name }}"
          VERSION=${TAG_VERSION#v} # Remove a leading "v" if present, e.g., v0.0.49 becomes 0.0.49
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

  build:
    name: Build Wheels
    needs: prepare-version
    uses: ./.github/workflows/wheels.yml
    with:
      version: ${{ needs.prepare-version.outputs.version }}
    secrets: inherit

  pypi-publish:
    name: Publish Wheels to PyPI
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Collect Wheels
        run: |
          mkdir -p dist_collected
          find dist/ -name '*.whl' -exec cp {} dist_collected/ \;

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          packages-dir: dist_collected/
