name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        uses: ./.github/actions/free-disk-space

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          shared-key: "build"

      - name: Build with warnings as errors
        run: cargo build --all-targets
        env:
          RUSTFLAGS: "-D warnings"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          shared-key: "lint"

      - name: Run cargo fmt
        run: cargo fmt

      - name: Run cargo clippy
        run: cargo clippy

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        uses: ./.github/actions/free-disk-space
        with:
          level: "maximum"

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          shared-key: "unit-tests"

      - name: Run unit tests
        run: make unit-tests

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [aws, azure]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        uses: ./.github/actions/free-disk-space

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          shared-key: "integration-${{ matrix.provider }}"

      - name: Run integration tests for ${{ matrix.provider }}
        run: |
          make ${{ matrix.provider }}-integration-tests

  docker-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: cli
            dockerfile: cli/Dockerfile
          - package: gitops
            dockerfile: gitops/Dockerfile.lambda
          - package: reconciler
            dockerfile: reconciler/Dockerfile.lambda
          - package: terraform_runner
            dockerfile: terraform_runner/Dockerfile.terraform
          - package: terraform_runner
            dockerfile: terraform_runner/Dockerfile.tofu
          - package: webserver-openapi
            dockerfile: webserver-openapi/Dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.package }} package using ${{ matrix.dockerfile }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false
          cache-from: type=gha,scope=${{ matrix.package }}-${{ hashFiles(matrix.dockerfile) }}
          cache-to: type=gha,mode=max,scope=${{ matrix.package }}-${{ hashFiles(matrix.dockerfile) }}

  python-builds:
    uses: ./.github/workflows/wheels.yml
    with:
      version: "0.0.0+to.be.overriden"
